#!/usr/bin/env python3
"""
Vexyon Bridge Daemon
====================
Single source of truth flows one way: shell.json -> Hyprland.

Responsibilities:
  * Read ~/.config/vexyon/shell.json
  * Generate ~/.config/hypr/vexyon-keybinds.conf  (keybinds + mouse binds + workspace binds)
  * Generate ~/.config/hypr/vexyon-settings.conf   (gaps / border / rounding from layout tokens)
  * Trigger `hyprctl reload` so changes apply live, zero restart
  * Watch shell.json (mtime poll, dependency-free) and regenerate on change

All writes are atomic (temp file + os.replace) so a crash mid-write never corrupts config.

Usage:
  vexyon-bridge.py            # daemon: generate once, then watch forever
  vexyon-bridge.py --oneshot  # generate once and exit (used by install.sh / manual regen)
"""

import json
import os
import sys
import time
import shutil
import subprocess

HOME = os.path.expanduser("~")
VEXYON_DIR = os.path.join(HOME, ".config", "vexyon")
HYPR_DIR = os.path.join(HOME, ".config", "hypr")
SHELL_JSON = os.path.join(VEXYON_DIR, "shell.json")
KEYBINDS_CONF = os.path.join(HYPR_DIR, "vexyon-keybinds.conf")
SETTINGS_CONF = os.path.join(HYPR_DIR, "vexyon-settings.conf")
MONITORS_CONF = os.path.join(HYPR_DIR, "vexyon-monitors.conf")

# Terminal theming targets (regenerated from the active Vexyon palette).
THEMES_DIR = os.path.join(HOME, ".local", "share", "vexyon", "themes")
GHOSTTY_CONF = os.path.join(HOME, ".config", "ghostty", "config")
FISH_THEME = os.path.join(HOME, ".config", "fish", "conf.d", "vexyon-theme.fish")
FASTFETCH_CONF = os.path.join(VEXYON_DIR, "fastfetch.jsonc")

POLL_INTERVAL = 0.5  # seconds

HEADER = (
    "# ============================================================================\n"
    "#  VEXYON — AUTOGENERATED. DO NOT EDIT BY HAND.\n"
    "#  Edit ~/.config/vexyon/shell.json (or use the Keybind Editor); the bridge\n"
    "#  daemon regenerates this file and reloads Hyprland automatically.\n"
    "# ============================================================================\n\n"
)


def log(msg):
    print(f"[vexyon-bridge] {msg}", flush=True)


def load_config():
    """Read shell.json. Returns dict or None on failure (caller keeps last good)."""
    try:
        with open(SHELL_JSON, "r") as f:
            return json.load(f)
    except FileNotFoundError:
        log(f"config not found: {SHELL_JSON}")
        return None
    except json.JSONDecodeError as e:
        log(f"invalid JSON in shell.json ({e}); keeping last good config")
        return None


def atomic_write(path, content):
    """Write content to path atomically (temp file in same dir + os.replace)."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        f.write(content)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, path)


def fmt_mods(mods):
    """['SUPER','SHIFT'] -> 'SUPER SHIFT'; [] -> ''."""
    return " ".join(mods) if mods else ""


def build_keybinds_conf(cfg):
    lines = [HEADER]
    lines.append("# --- Static core mouse binds ---\n")
    lines.append("gesture = 3, horizontal, workspace\n")
    for mb in cfg.get("mouseBinds", []):
        mods = fmt_mods(mb.get("mods", []))
        lines.append(f"bindm = {mods}, {mb['button']}, {mb['action']}\n")
    lines.append("\n# --- Named action binds ---\n")

    for kb in cfg.get("keybinds", []):
        mods = fmt_mods(kb.get("mods", []))
        key = kb["key"]
        action = kb["action"]
        arg = kb.get("arg", "")
        # Optional per-bind Hyprland flags: 'l' (works while locked) and
        # 'e' (repeats while held) — used by the multimedia keys. Anything
        # else is dropped so a corrupt value can't emit invalid config.
        flags = "".join(c for c in str(kb.get("flags", "")) if c in "le")
        bind = f"bind{flags}"
        if action == "exec":
            line = f"{bind} = {mods}, {key}, exec, {arg}"
        elif action == "global":
            # Quickshell GlobalShortcut: appid 'quickshell', name = arg
            line = f"{bind} = {mods}, {key}, global, quickshell:{arg}"
        elif action == "dispatch":
            # Hyprland wants: bind = MODS, key, <dispatcher>, <params>
            # so split the dispatcher from its params on the first space.
            parts = arg.split(" ", 1)
            if len(parts) == 2:
                line = f"{bind} = {mods}, {key}, {parts[0]}, {parts[1]}"
            else:
                line = f"{bind} = {mods}, {key}, {parts[0]}"
        else:
            log(f"unknown action '{action}' for keybind '{kb.get('id')}', skipping")
            continue
        lines.append(line + f"    # {kb.get('desc','')}\n")

    # --- Workspace switch / move binds (generated, follow-the-window) ---
    lines.append("\n# --- Workspace binds (generated from workspaceCount) ---\n")
    count = cfg.get("layout", {}).get("workspaceCount", 10)
    count = max(1, min(count, 10))
    km = cfg.get("keybindMods", {})
    sw_mods = fmt_mods(km.get("workspaceSwitch", ["SUPER"]))
    mv_mods = fmt_mods(km.get("workspaceMove", ["SUPER", "SHIFT"]))
    for i in range(1, count + 1):
        key = str(i % 10)  # 10 -> '0'
        lines.append(f"bind = {sw_mods}, {key}, workspace, {i}\n")
    for i in range(1, count + 1):
        key = str(i % 10)
        # NON-silent movetoworkspace: the user FOLLOWS the window to the target workspace.
        lines.append(f"bind = {mv_mods}, {key}, movetoworkspace, {i}\n")

    return "".join(lines)


def fmt_scale(s):
    """1 -> '1', 1.25 -> '1.25' (trim trailing zeros; Hyprland wants a clean float)."""
    try:
        n = float(s)
    except (TypeError, ValueError):
        return "1"
    if n <= 0:
        return "1"
    return ("%f" % n).rstrip("0").rstrip(".") or "1"


def monitor_line(name, c):
    """Build the Hyprland `monitor =` value from a per-monitor config dict.
    Mirrors Displays.monLine() in QML so live-apply and persisted conf agree."""
    if c.get("enabled") is False:
        return f"{name}, disable"
    res = f"{c.get('resolution', 'preferred')}@{c.get('refresh', 60)}"
    pos = f"{int(c.get('x', 0))}x{int(c.get('y', 0))}"
    line = f"{name}, {res}, {pos}, {fmt_scale(c.get('scale', 1))}"
    line += f", transform, {int(c.get('transform', 0))}"
    line += f", vrr, {int(c.get('vrr', 0))}"
    if int(c.get("bitdepth", 8)) == 10:
        line += ", bitdepth, 10"
    return line


def build_monitors_conf(cfg):
    """Translate the active display profile into monitor= lines. When there is no
    active profile (or it has no monitors), emit nothing so the base catch-all
    `monitor = , preferred, auto, 1` in hyprland.conf stays in effect."""
    lines = [HEADER]
    lines.append("# Generated from shell.json displays.activeProfile.\n")
    disp = cfg.get("displays", {}) or {}
    active = disp.get("activeProfile", "")
    profile = None
    for p in disp.get("profiles", []) or []:
        if p.get("name") == active:
            profile = p
            break
    if not profile or not profile.get("monitors"):
        lines.append("# (no active profile — hyprland.conf default applies)\n")
        return "".join(lines)
    lines.append(f"# Active profile: {active}\n")
    for name, c in profile["monitors"].items():
        lines.append(f"monitor = {monitor_line(name, c)}\n")
    return "".join(lines)


def build_settings_conf(cfg):
    layout = cfg.get("layout", {})
    behavior = cfg.get("behavior", {})
    appearance = cfg.get("appearance", {})
    gaps_in = layout.get("gapsIn", 4)
    gaps_out = layout.get("gapsOut", 10)
    border = layout.get("borderSize", 2)
    rounding = layout.get("roundingHypr", 12)
    ffm = 1 if behavior.get("focusFollowsMouse", True) else 0
    # Distribución de teclado (Ajustes → Comportamiento). Solo caracteres XKB
    # válidos — un valor corrupto en shell.json no debe romper la config.
    kb = str(behavior.get("keyboardLayout", "us")).strip() or "us"
    if not all(c.isalnum() or c in ",_-" for c in kb):
        kb = "us"

    # Blur de la barra (appearance.barBlur). Gramática de layerrule VERIFICADA
    # en vivo contra Hyprland 0.55.4 (hyprctl keyword devuelve ok; la forma
    # legacy `ignorealpha` la rechaza con "invalid field type"):
    #     layerrule = blur on, match:namespace ^(vexyon-bar)$
    #     layerrule = ignore_alpha 0.2, match:namespace ^(vexyon-bar)$
    # El blur global de decoration debe estar ON para que la layerrule surta
    # efecto; las ventanas son opacas (active_opacity 1.0) y los popups usan
    # otros namespaces sin regla, así que solo la barra se desenfoca.
    # ignore_alpha deja sin blur los píxeles casi transparentes (esquinas
    # redondeadas de la píldora y el hueco del edgeGap) — sin él saldría un
    # halo rectangular alrededor de la barra flotante.
    bar_blur = appearance.get("barBlur", True) is not False
    intensity = appearance.get("barBlurIntensity", 24)
    blur_size = max(2, min(int(intensity / 4), 14))

    # Bordes de ventana desde la paleta del tema activo (mismos tokens que
    # ghostty/fish/fastfetch): activa = degradado accent→accent2 45deg (el
    # mismo lenguaje visual que traía el bloque estático, pero temado),
    # inactiva = surface1 atenuada. Viven AQUÍ y no en el bloque estático de
    # hyprland.conf: cualquier valor ahí pisaría éste (última asignación
    # gana) y el cambio de tema no se reflejaría.
    colors, _ = load_theme(cfg)
    body = (
        HEADER
        + "general {\n"
        + f"    gaps_in = {gaps_in}\n"
        + f"    gaps_out = {gaps_out}\n"
        + f"    border_size = {border}\n"
        + f"    col.active_border = rgba({theme_hex(colors, 'accent')}ff) rgba({theme_hex(colors, 'accent2')}ff) 45deg\n"
        + f"    col.inactive_border = rgba({theme_hex(colors, 'surface1')}aa)\n"
        + "}\n\n"
        + "decoration {\n"
        + f"    rounding = {rounding}\n"
        + "    blur {\n"
        + f"        enabled = {'true' if bar_blur else 'false'}\n"
        + f"        size = {blur_size}\n"
        + "        passes = 3\n"
        + "    }\n"
        + "}\n\n"
        + "input {\n"
        + f"    kb_layout = {kb}\n"
        + f"    follow_mouse = {ffm}\n"
        + "}\n"
    )
    if bar_blur:
        body += (
            "\n# Blur SOLO en la barra (appearance.barBlur)\n"
            "layerrule = blur on, match:namespace ^(vexyon-bar)$\n"
            "layerrule = ignore_alpha 0.2, match:namespace ^(vexyon-bar)$\n"
        )
    return body


# ============================================================================
#  Terminal theming: Ghostty + Fish + fastfetch, all from the active palette.
# ============================================================================
DEFAULTS = {
    "base": "#0d0d12", "mantle": "#0a0a0e", "crust": "#070709",
    "text": "#e6e6ef", "subtext0": "#a6a6c0", "subtext1": "#c2c2d6",
    "surface0": "#16161d", "surface1": "#20202a", "surface2": "#2b2b38",
    "overlay0": "#3a3a4a", "overlay1": "#4c4c60", "overlay2": "#6a6a82",
    "accent": "#e11d48", "accent2": "#f43f5e",
    "red": "#f38ba8", "green": "#a6e3a1", "yellow": "#f9e2af", "blue": "#89b4fa",
    "peach": "#fab387", "mauve": "#cba6f7", "teal": "#94e2d5", "pink": "#f5c2e7",
}


def load_theme(cfg):
    """Return (colors_dict, is_dark) for the active theme, filled with fallbacks."""
    active = (cfg.get("theme", {}) or {}).get("active", "crimson-voltage")
    colors = dict(DEFAULTS)
    is_dark = True
    try:
        with open(os.path.join(THEMES_DIR, active + ".json")) as f:
            data = json.load(f)
        is_dark = data.get("dark", True) is not False
        for k, v in (data.get("colors", {}) or {}).items():
            if v:
                colors[k] = v
    except Exception as e:
        log(f"theme '{active}' not loaded ({e}); using fallback palette")
    if "onAccent" not in colors:
        colors["onAccent"] = "#0b0b0f" if is_dark else "#ffffff"
    return colors, is_dark


def hexstrip(h):
    return h.lstrip("#")


def theme_hex(colors, key):
    """6 dígitos hex validados para sintaxis rgba() de Hyprland — un color
    corrupto en un theme JSON no debe emitir config inválida."""
    s = hexstrip(str(colors.get(key, ""))).lower()
    if len(s) != 6 or any(ch not in "0123456789abcdef" for ch in s):
        s = hexstrip(DEFAULTS[key])
    return s


def hex_to_ansi(h):
    """'#e11d48' -> '38;2;225;29;72' (fastfetch truecolor spec)."""
    s = hexstrip(h)
    try:
        r, g, b = int(s[0:2], 16), int(s[2:4], 16), int(s[4:6], 16)
        return f"38;2;{r};{g};{b}"
    except Exception:
        return "38;2;225;29;72"


def build_ghostty_conf(cfg, c):
    font = (cfg.get("appearance", {}) or {}).get("fontFamily", "JetBrainsMono Nerd Font")
    # ANSI slots: 0-7 normal, 8-15 bright.
    ansi = [c["surface1"], c["red"], c["green"], c["yellow"], c["blue"], c["mauve"],
            c["teal"], c["subtext1"], c["overlay1"], c["red"], c["green"], c["yellow"],
            c["blue"], c["mauve"], c["teal"], c["text"]]
    lines = [
        "# AUTOGENERATED by vexyon-bridge — regenerated on theme change. Do not edit.",
        "command = /usr/bin/fish",
        f"font-family = {font}",
        f"background = {c['base']}",
        f"foreground = {c['text']}",
        f"cursor-color = {c['accent']}",
        f"selection-background = {c['accent']}",
        f"selection-foreground = {c['onAccent']}",
    ]
    for i, col in enumerate(ansi):
        lines.append(f"palette = {i}={col}")
    return "\n".join(lines) + "\n"


def build_fish_theme(c):
    """Fish syntax-highlight colours + a themed two-tone prompt (native fish)."""
    def s(h):
        return hexstrip(h)
    lines = [
        "# AUTOGENERATED by vexyon-bridge — regenerated on theme change. Do not edit.",
        f"set -g fish_color_normal {s(c['text'])}",
        f"set -g fish_color_command {s(c['blue'])}",
        f"set -g fish_color_keyword {s(c['mauve'])}",
        f"set -g fish_color_quote {s(c['green'])}",
        f"set -g fish_color_redirection {s(c['teal'])}",
        f"set -g fish_color_end {s(c['peach'])}",
        f"set -g fish_color_error {s(c['red'])}",
        f"set -g fish_color_param {s(c['subtext1'])}",
        f"set -g fish_color_comment {s(c['overlay1'])}",
        f"set -g fish_color_operator {s(c['yellow'])}",
        f"set -g fish_color_escape {s(c['pink'])}",
        f"set -g fish_color_autosuggestion {s(c['overlay0'])}",
        f"set -g fish_color_selection --background={s(c['surface2'])}",
        f"set -g fish_color_search_match --background={s(c['surface1'])}",
        f"set -g fish_pager_color_prefix {s(c['accent'])}",
        f"set -g fish_pager_color_progress {s(c['subtext0'])}",
        f"set -g fish_pager_color_selected_background --background={s(c['surface1'])}",
        f"set -g vexyon_accent {s(c['accent'])}",
        f"set -g vexyon_accent2 {s(c['accent2'])}",
        f"set -g vexyon_muted {s(c['subtext0'])}",
        "",
        "function fish_prompt",
        "    set -l st $status",
        "    set_color $vexyon_muted",
        "    echo -n (whoami)'@'(prompt_hostname)' '",
        "    set_color $vexyon_accent",
        "    echo -n (prompt_pwd)",
        "    echo -n ' '",
        "    if test $st -eq 0",
        "        set_color $vexyon_accent2",
        "    else",
        "        set_color $fish_color_error",
        "    end",
        "    echo -n '❯ '",
        "    set_color normal",
        "end",
        "",
    ]
    return "\n".join(lines) + "\n"


def build_fastfetch_conf(c):
    keys = hex_to_ansi(c["accent"])
    title = hex_to_ansi(c["accent2"])
    logo1 = hex_to_ansi(c["accent"])
    logo2 = hex_to_ansi(c["accent2"])
    data = {
        "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
        # Compact "small" logo: the full auto logo (~40 cols wide) overflowed and
        # garbled the output whenever a terminal was tiled narrow (several open at
        # once). The small logo keeps the greeting clean down to half-width tiles.
        "logo": {"type": "small", "padding": {"top": 1, "right": 1},
                 "color": {"1": logo1, "2": logo2}},
        "display": {"separator": "  ", "color": {"keys": keys, "title": title}},
        "modules": [
            {"type": "title", "color": {"user": keys, "at": title, "host": keys}},
            {"type": "separator", "string": "─"},
            {"type": "os", "key": "OS"},
            {"type": "kernel", "key": "Kernel"},
            {"type": "uptime", "key": "Uptime"},
            {"type": "packages", "key": "Packages"},
            {"type": "shell", "key": "Shell"},
            {"type": "terminal", "key": "Terminal"},
            {"type": "wm", "key": "WM"},
            # Compact CPU/disk formats: full defaults ("… (32) @ 3.19 GHz",
            # "… - ext4") overran narrow tiled terminals. Drop cores/freq/fs.
            {"type": "cpu", "key": "CPU", "format": "{name}"},
            {"type": "gpu", "key": "GPU", "format": "{name}"},
            {"type": "memory", "key": "Memory"},
            {"type": "disk", "key": "Disk", "format": "{size-used} / {size-total} ({size-percentage})"},
            "break",
            {"type": "colors", "symbol": "circle"},
        ],
    }
    return json.dumps(data, indent=2) + "\n"


def ghostty_reload():
    """Ghostty reloads its config on SIGUSR2 -> open terminals re-theme live."""
    if shutil.which("pkill"):
        subprocess.run(["pkill", "-SIGUSR2", "ghostty"], check=False,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def regenerate_terminal(cfg):
    colors, _ = load_theme(cfg)
    atomic_write(GHOSTTY_CONF, build_ghostty_conf(cfg, colors))
    atomic_write(FISH_THEME, build_fish_theme(colors))
    atomic_write(FASTFETCH_CONF, build_fastfetch_conf(colors))
    ghostty_reload()
    log("regenerated ghostty/fish/fastfetch theme + signalled Ghostty reload")


def hyprctl_reload():
    if not shutil.which("hyprctl"):
        log("hyprctl not found; skipping reload (not in a Hyprland session?)")
        return
    try:
        subprocess.run(["hyprctl", "reload"], check=False,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=10)
        log("hyprctl reload triggered")
    except Exception as e:
        log(f"hyprctl reload failed: {e}")


def regenerate(cfg, reload=True):
    atomic_write(KEYBINDS_CONF, build_keybinds_conf(cfg))
    atomic_write(SETTINGS_CONF, build_settings_conf(cfg))
    atomic_write(MONITORS_CONF, build_monitors_conf(cfg))
    log(f"regenerated {os.path.basename(KEYBINDS_CONF)} + {os.path.basename(SETTINGS_CONF)} + {os.path.basename(MONITORS_CONF)}")
    regenerate_terminal(cfg)
    if reload:
        hyprctl_reload()


def main():
    oneshot = "--oneshot" in sys.argv
    cfg = load_config()
    if cfg is None:
        log("no valid config on startup; nothing to generate")
        if oneshot:
            sys.exit(1)
    else:
        # On the very first generation don't reload if oneshot from installer
        regenerate(cfg, reload=not oneshot)

    if oneshot:
        return

    last_mtime = os.path.getmtime(SHELL_JSON) if os.path.exists(SHELL_JSON) else 0
    last_good = cfg
    log("watching shell.json for changes...")
    while True:
        time.sleep(POLL_INTERVAL)
        try:
            mtime = os.path.getmtime(SHELL_JSON)
        except FileNotFoundError:
            continue
        if mtime == last_mtime:
            continue
        last_mtime = mtime
        new_cfg = load_config()
        if new_cfg is None:
            continue  # malformed; keep last good, wait for next save
        if new_cfg == last_good:
            continue  # touched but identical
        last_good = new_cfg
        log("shell.json changed -> regenerating + reloading")
        regenerate(new_cfg, reload=True)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
